### ISSUE TITLE
Error after run ingest from docker

### ISSUE THREAD

**Issue by Yutwizard** [PacktPublishing/Machine-Learning-for-Algorithmic-Trading-Second-Edition_Original#5]
After run zipline ingest error show below how to solve it?

(ml4t-zipline) packt@1880ba20f414:~/ml4t$ zipline ingest
Traceback (most recent call last):
  File "/opt/conda/envs/ml4t-zipline/bin/zipline", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/zipline/__main__.py", line 60, in main
    os.environ,
  File "/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/zipline/utils/run_algo.py", line 249, in load_extensions
    pth.ensure_file(default_extension_path)
  File "/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/zipline/utils/paths.py", line 58, in ensure_file
    ensure_directory_containing(path)
  File "/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/zipline/utils/paths.py", line 45, in ensure_directory_containing
    ensure_directory(os.path.dirname(path))
  File "/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/zipline/utils/paths.py", line 30, in ensure_directory
    os.makedirs(path)
  File "/opt/conda/envs/ml4t-zipline/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/conda/envs/ml4t-zipline/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/packt/ml4t/data'

**Comment by stefan-jansen** [comment]
Are you on Windows? If so, you may have to give Docker permissions to access your drive as described [here](https://rominirani.com/docker-on-windows-mounting-host-directories-d96f3f056a2c).

**Comment by stefan-jansen** [comment]
Also, please use the source repo at https://github.com/stefan-jansen/machine-learning-for-trading, Packt is not keeping this clone up to date.
